---
# SETUP HONO using Helm
# TODO: replace with enmasse operator

- name: Create Hono namespace
  shell: kubectl create namespace {{ hono_namespace }}
  register: hono_create_namespace_cmd
  failed_when: hono_create_namespace_cmd.stderr != '' and 'AlreadyExists' not in hono_create_namespace_cmd.stderr

- name: Set context to Hono namespace
  shell: kubectl config set-context $(kubectl config current-context) --namespace={{ hono_namespace }}

- name: Add the Eclipse IoT repository
  shell: helm repo add eclipse-iot https://eclipse.org/packages/charts

- name: Update helm repos
  shell: helm repo update

- name: Install Hono using Helm
  shell: |
    helm install --dependency-update -n {{ hono_namespace }} --set adapters.amqp.enabled=false --set prometheus.createInstance=false --set grafana.enabled=false hono eclipse-iot/hono --version {{ hono_chart_version }}