---
- name: "Verify EnMasse deployment succeeded"
  block:
    # TODO: check this pod is present before going on to check all are running
    - name: Ensure iot-http-adapter is present
      shell: kubectl get --no-headers=true pod -l name=iot-http-adapter --namespace {{ enmasse_namespace }}  |  grep -v "Running"
      register: result
      until: not result.stdout
      retries: 50
      delay: 10
      failed_when: result.stdout
      changed_when: False
    - name: Ensure all pods in the enmasse namespace are running
      shell: kubectl get --no-headers=true pod --namespace {{ enmasse_namespace }}  |  grep -v "Running"
      register: result
      until: not result.stdout
      retries: 50
      delay: 10
      failed_when: result.stdout
      changed_when: False