---
app_host: abc.re.je

ns_prefix: ''

eval_enmasse_namespace: "{{ ns_prefix | default('')}}enmasse"
eval_grafana_namespace: "{{ ns_prefix | default('')}}grafana"
eval_influxdb_namespace: "{{ ns_prefix | default('')}}influxdb"
eval_hono_namespace: "{{ ns_prefix | default('')}}hono"
eval_connector_namespace: "{{ ns_prefix | default('')}}connector"
# eval_cert_manager_namespace: "{{ ns_prefix | default('')}}cert-manager"

working_dir: "{{ lookup('env','PWD') }}"

kaniko_secret: "{{ working_dir }}/kaniko-secret.json"
dns_admin_secret: "{{ working_dir }}/key.json"
gke_project: ""

aws_s3_backup_secret_name: 's3-credentials'

backup_s3_aws_access_key: ""
backup_s3_aws_secret_key: ""
backup_s3_aws_bucket: ""