---
abc_cloud_version: master

# influxdb
influxdb: True
influxdb_version: "1.7.10"
# swap from master to release version on first release
influxdb_operator_release_tag: "06eb678"
influxdb_operator_resources: "https://raw.githubusercontent.com/influxdata/influxdata-operator/{{ influxdb_operator_release_tag }}/deploy"
# custom build for abc swap to official when released or set up CI/CD to auto build updates
influxdb_operator_build_image: "gcr.io/sodium-apex-265111/influxdb-operator:{{ influxdb_operator_release_tag }}"

# grafana
grafana: True
grafana_operator_release_tag: "v3.1.0"
grafana_operator_resources: "https://raw.githubusercontent.com/integr8ly/grafana-operator/{{ grafana_operator_release_tag }}/deploy"

# hono (Helm)
hono: True
hono_chart_version: "v1.3.0"
hono_default_device: True

# hono_influxdb_connector
connector: True
# TODO: Swap to release when fixes are tagged
connector_release_tag: "036c28f"
connector_build_image: "gcr.io/sodium-apex-265111/hono-influxdb-connector"

# cert-manager
cert_manager: True
cert_manager_version: "v0.14.1"

# lets encrypt (used by cert-manager)
# use production or staging environment
lets_encrypt_prod: True
lets_encrypt_email: user@example.com
# lets_encrypt_challenge: DNS01 # HTTP01 OR DNS01
# lets_encrypt_dns_provider: route53

# external_dns
external_dns: True

# enmasse
enmasse: True
enmasse_version: '0.31.0'
enmasse_release_url: https://github.com/EnMasseProject/enmasse/releases/download/{{ enmasse_version }}/enmasse-{{ enmasse_version }}.tgz
enmasse_default_project: myapp
# enmasse_postgresql_image: 'postgresql:9.6'