---
abc_cloud_version: master

# influxdb
influxdb: True
influxdb_version: "1.7.10"
# swap from master to release version on first release
influxdb_operator_release_tag: "master"
influxdb_operator_resources: "https://raw.githubusercontent.com/influxdata/influxdata-operator/{{ influxdb_operator_release_tag }}/deploy"
# custom build for abc swap to official when released or set up CI/CD to auto build updates
influxdb_operator_build_image: "gcr.io/sodium-apex-265111/influxdb-operator"

# grafana
grafana: True
grafana_operator_release_tag: "v3.1.0"
grafana_operator_resources: "https://raw.githubusercontent.com/integr8ly/grafana-operator/{{ grafana_operator_release_tag }}/deploy"


# hono (Helm)
hono: True
hono_chart_version: "v1.3.0"

# hono_influxdb_connector
connector: True
# TODO: Swap to release when fixes are tagged
connector_release_tag: "036c28f"
connector_build_image: "gcr.io/sodium-apex-265111/hono-influxdb-connector"

# # enmasse
# enmasse: True
# enmasse_version: '1.3.2'
# enmasse_git_url: https://github.com/jboss-container-images/amq-online-images.git
