grafana_namespace: grafana

grafana_operator_resource_items:
  - "{{ grafana_operator_resources }}/crds/Grafana.yaml"
  - "{{ grafana_operator_resources }}/crds/GrafanaDataSource.yaml"
  - "{{ grafana_operator_resources }}/crds/GrafanaDashboard.yaml"
  # - "{{ grafana_operator_resources }}/cluster_roles/cluster_role_grafana_operator.yaml"
  - "{{ grafana_operator_resources }}/roles/service_account.yaml"
  - "{{ grafana_operator_resources }}/roles/role.yaml"
  - "{{ grafana_operator_resources }}/roles/role_binding.yaml"
  - "{{ grafana_operator_resources }}/operator.yaml"

  
# grafana_admin_username: grafanaadmin
# grafana_admin_token: admintoken
# grafana_admin_password: Password1
